# Generated by Django 4.0.2 on 2022-03-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateField()),
                ('FTEhourByDay', models.FloatField()),
                ('ExtraHour', models.FloatField()),
                ('Absenteeism_ratio', models.FloatField()),
                ('Unproductiveness_ratio', models.FloatField()),
                ('Efficienty_ratio', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('program', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('planning', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=200)),
                ('workstation', models.CharField(max_length=200)),
                ('AllocatedTime', models.FloatField()),
                ('Leadtime', models.FloatField()),
                ('Delta_First_Def_And_StartManuf', models.FloatField(verbose_name='First Def And Start Manuf')),
                ('Delta_Last_Def_And_End_Of_Manuf', models.FloatField(verbose_name='Last Def And End Manuf')),
                ('Delta_Buffer_OTD', models.FloatField()),
                ('Allocated_Time_On_Workstation', models.FloatField()),
                ('Smooth_Family', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HolidaysCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('holidaysDate', models.DateField()),
                ('user_id', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
