# Generated by Django 4.0.2 on 2022-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdata',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
