# Generated by Django 4.0.2 on 2022-04-04 13:27

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_traitement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workdata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.CreateModel(
            name='CalendarConfigurationTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('Version', models.CharField(max_length=200)),
                ('TraitementNumber', models.IntegerField()),
                ('EndDate', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.models.SoftDeleteManager),
        ),
        migrations.CreateModel(
            name='calendarConfigurationCpordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('msn', models.IntegerField()),
                ('first_def', models.IntegerField()),
                ('last_def', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.models.SoftDeleteManager),
        ),
    ]
