# Generated by Django 4.0.2 on 2022-04-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_has_traitement_alter_workdata_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfigurationcpordo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarconfigurationtraitement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendarconfigurationcpordo',
            name='first_def',
            field=models.IntegerField(verbose_name='First Def'),
        ),
        migrations.AlterField(
            model_name='calendarconfigurationcpordo',
            name='last_def',
            field=models.IntegerField(verbose_name='Last Def '),
        ),
        migrations.AlterField(
            model_name='calendarconfigurationtraitement',
            name='EndDate',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='calendarconfigurationtraitement',
            name='TraitementNumber',
            field=models.IntegerField(verbose_name='Traitement Number'),
        ),
    ]
