# Generated by Django 4.0.2 on 2022-04-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calendarconfigurationcpordo_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConfigurationTreatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Version', models.CharField(max_length=200)),
                ('TreatementNumber', models.IntegerField(verbose_name='Treatment Number')),
                ('EndDate', models.DateField(verbose_name='End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='has_traitement',
            new_name='has_treatement',
        ),
        migrations.DeleteModel(
            name='CalendarConfigurationTraitement',
        ),
        migrations.AddField(
            model_name='calendarconfigurationtreatement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
