# Generated by Django 4.0.2 on 2022-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calendarconfigurationtreatement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('division', models.IntegerField(null=True)),
                ('profit_centre', models.CharField(max_length=50, null=True)),
                ('order', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('order_type', models.CharField(max_length=50, null=True)),
                ('order_quantity', models.IntegerField()),
                ('date_start_plan', models.DateField(null=True)),
                ('date_end_plan', models.DateField(null=True)),
                ('fixation', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=50, null=True)),
                ('order_stat', models.CharField(max_length=50, null=True)),
                ('customer_order', models.CharField(max_length=50, null=True)),
                ('date_end_real', models.DateField(null=True)),
                ('entered_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
