# Generated by Django 4.0.2 on 2022-04-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_zpp_alter_calendarconfigurationcpordo_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zpp',
        ),
    ]
