# Generated by Django 4.0.2 on 2022-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_zpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=50, null=True)),
                ('plan_date', models.DateField(null=True)),
                ('element', models.CharField(max_length=50, null=True)),
                ('data_element_planif', models.CharField(max_length=100, null=True)),
                ('message', models.IntegerField(null=True)),
                ('needs', models.FloatField()),
                ('qte_available', models.FloatField()),
                ('date_reordo', models.DateField(null=True)),
                ('supplier', models.CharField(max_length=50, null=True)),
                ('customer', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
