# Generated by Django 4.0.2 on 2022-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_zpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpp',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zpp',
            name='needs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zpp',
            name='qte_available',
            field=models.FloatField(null=True),
        ),
    ]
