# Generated by Django 4.0.2 on 2022-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_zpp_customer_alter_zpp_needs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpp',
            name='message',
            field=models.FloatField(null=True),
        ),
    ]
