# Generated by Django 4.0.2 on 2022-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_zpp_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayscalendar',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workdata',
            name='Absenteeism_ratio',
        ),
        migrations.RemoveField(
            model_name='workdata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='holidayscalendar',
            name='owner',
            field=models.CharField(default='officiel', max_length=30),
        ),
        migrations.AddField(
            model_name='workdata',
            name='owner',
            field=models.CharField(default='officiel', max_length=30),
        ),
    ]
