# Generated by Django 4.0.2 on 2022-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_holidayscalendar_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdata',
            name='Absenteeism_ratio',
            field=models.FloatField(null=True),
        ),
    ]
