# Generated by Django 4.0.2 on 2022-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_workdata_absenteeism_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='Absenteeism_ratio',
            field=models.FloatField(),
        ),
    ]
