# Generated by Django 4.0.2 on 2022-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_workdata_absenteeism_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfigurationcpordo',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconfigurationcpordo',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='calendarconfigurationcpordo',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconfigurationcpordo',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='calendarconfigurationtreatement',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconfigurationtreatement',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='calendarconfigurationtreatement',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconfigurationtreatement',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coois',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coois',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='coois',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coois',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='division',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holidayscalendar',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='holidayscalendar',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='holidayscalendar',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='holidayscalendar',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='material',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workdata',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workdata',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='workdata',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workdata',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='zpp',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zpp',
            name='deleted_by',
            field=models.CharField(default='Marwa', max_length=30),
        ),
        migrations.AddField(
            model_name='zpp',
            name='restored_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='zpp',
            name='restored_by',
            field=models.CharField(default='Marwa', max_length=30, null=True),
        ),
    ]
