# Generated by Django 4.0.2 on 2022-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_calendarconfigurationcpordo_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopfloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(default='Marwa', max_length=30)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('restored_at', models.DateTimeField(auto_now=True, null=True)),
                ('restored_by', models.CharField(default='Marwa', max_length=30, null=True)),
                ('division', models.IntegerField(null=True)),
                ('profit_centre', models.CharField(max_length=50, null=True)),
                ('order', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('order_type', models.CharField(max_length=50, null=True)),
                ('order_quantity', models.IntegerField()),
                ('date_start_plan', models.DateField(null=True)),
                ('date_end_plan', models.DateField(null=True)),
                ('fixation', models.CharField(max_length=50, null=True)),
                ('date_reordo', models.DateField(null=True)),
                ('message', models.FloatField(null=True)),
                ('order_stat', models.CharField(max_length=50, null=True)),
                ('customer_order', models.CharField(max_length=50, null=True)),
                ('date_end_real', models.DateField(null=True)),
                ('AllocatedTime', models.FloatField()),
                ('Leadtime', models.FloatField()),
                ('workstation', models.CharField(max_length=200)),
                ('Allocated_Time_On_Workstation', models.FloatField()),
                ('Smooth_Family', models.CharField(max_length=50)),
                ('Ranking', models.CharField(max_length=50, null=True)),
                ('Freeze_end_date', models.DateField(null=True)),
                ('Remain_to_do', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
