# Generated by Django 4.0.2 on 2022-05-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_shopfloor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopfloor',
            old_name='division',
            new_name='plant',
        ),
    ]
