# Generated by Django 4.0.2 on 2022-05-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_division_shopfloor_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopfloor',
            old_name='plant',
            new_name='division',
        ),
    ]
